language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-modo-static' ]; then cd .. && eval "mv $currentfolder generator-modo-static" && cd generator-modo-static; fi

